name: tiu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  # Gerenciador de estados
  get: ^4.6.5
  # Google
  google_fonts: ^3.0.1  
  # Back4app
  parse_server_sdk_flutter: ^3.1.2
  # upload Files
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.8
  #upload file
  file_picker: ^4.6.1
  # flutter.dev
  url_launcher: ^6.1.2
  # outros
  uuid: ^3.0.6
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/